### ISSUE TITLE
Error: Timeout - 200ms elapsed at eval

### ISSUE THREAD

**Issue by biloo-dev** [geblanco/electron-router#12]
hi fiends  !!
I got this error when I used axios with the electron in Main Process to fetch data from electron .

Error: Timeout - 200ms elapsed at eval

**Comment by geblanco** [comment]
Hello @biloo-dev ,

I'm not acquainted with axios, maybe you can put a MWE?
In any case, that error triggers when you install a full-duplex handler but do not call the callback, maybe
a) you wanted a simple handler instead of a duplex one? (i.e.: `router.on(...)` or `router.send(...)` instead of `router.get(...)`
b) you forgot to call `res.json()` in the handler
c) your function is too slow? (you can increase the timeout parameter)

Best,

**Comment by geblanco** [comment]
@biloo-dev friendly ping :)

**Comment by geblanco** [comment]
Closing this, reopen if when you have new information!
